### PR TITLE
Serve a unique favicon per project! Solves issue #62

### PR DESCRIPTION
**Pull request by wmhilton**
What's needed:

favicon1 someone (besides me) to try it and see if they like it
favicon2 discuss!
favicon3 decide whether to document feature or have it become an Easter egg
favicon4 tests?

### CODE REVIEW

**Comment by jdormit** [comment]
I will be able to check it out tomorrow or Wednesday most likely.

**Comment by jdormit** [comment]
re: IE support, I think as long as this won't *break* IE, it's not super important that it works on IE.

**Comment by wmhilton** [comment]
@jdormit It turned out IE handles the favicons just fine, the problem was a IE's caching behavior is... aggressive. :)

**Comment by jdormit** [comment]
Looks good! Tested in a few browsers, and ensured that existing favicons will still get served if one exists.

**Comment by wmhilton** [comment]
Thanks for testing it out and merging @jdormit! 😄

**Pull request merged**
