### PR TITLE
Replace 'marky-markdown'with 'remark' to have Node 4 support back

### LINKED ISSUE #77: jus development stalled by Node 4 support
### Events summary

1. `node-oniguruma` [broke Node 4 support](https://github.com/atom/node-oniguruma/issues/65) on April 20
2. The above make `jus` development imposible 'cause of Travis
3. There has been three PRs ( #72, #73 and #74) to mitigate `jus` impact to no avail
4. `node-origumma` problem has been [fixed](https://github.com/atom/node-oniguruma/pull/71) on Sep. 8
5. `first-mate` is  [blocking the update to origuruma@7.0.0](https://github.com/atom/first-mate/blob/master/package.json#L25) in the dependency chain (marky-markdown > highlights > first-mate > oniguruma)

### Issue

`jus` development can not be done 'cause of Travis (I have not been able to PR since April 20)

#### a) Ask 'first-mate' to update oniguruma dependency

Create a `first-mate` PR with just one line change in their `package.json`. ~~The change consist in just one character `"oniguruma": "6.2.1",` to `"oniguruma": "^6.2.1",` ...and hope it gets merged.~~

EDIT: The change consist in  `"oniguruma": "6.2.1",` to `"oniguruma": "7.0.0",`

This may be difficult 'cause I see their tests and configurations stating Node 6 clearly and may not have an incentive to support Node 4 ...but you never know.

#### b) Change 'jus' Node support to 6

Create and merge a `jus` PR with the needed change.

### PR DESCRIPTION
**Pull request by elingerojo**
Fix #77 

Per @zeke [recommendation](https://github.com/jus/jus/pull/72#issuecomment-330211849), replaced `marky-markdown` with `remark`

- Node 4 support is back
- No more `oniguruma` dependency 🎉 

<sub>Note: This PR only needs `jus` version bump</sub>

### CODE REVIEW

**Comment by elingerojo** [comment]
Added plugins to substitute `marky-markdown` equivalent options:

- `remak-slug` to substitue "liknkfy" option
- `remark-highlight` to substitute "highlightSyntax" option

Tested with `jus.js.org` website but had problems with handlebars fenced code producing parse errors.

....so decided to add the option for "included languages" and did not include handlebars. This way, handlebars is not highlighted (it only appears as plain fenced code).

Note: This PR is a **breaking change**

**Comment by zeke** [comment]
marky-markdown is synchronous and remark is asynchronous, but this implementation doesn't seem to account for that. Am I missing something?

**Comment by elingerojo** [comment]
My bad.

Corrected.

Now `squeezed`is controlled asynchronously by `remak.proces()`

**Comment by zeke** [comment]
Sorry for the delay on this. @elingerojo is this ready to go?

I'm good with the changes, and can release this as a major version bump.

**Comment by djfdev** [comment]
We're at ~4 months radio silence from @elingerojo on this one. Would be great to merge this to allow further development on jus.

**Comment by zeke** [comment]
I'm gonna set up semantic-release on this repo, then I'll land this in a new major version: https://github.com/jus/jus/pull/83

**Pull request merged**
