### PR TITLE
fix: Replace 'body' in layout

### PR DESCRIPTION
**Pull request by TiagoDanin**
Problem ? 
```
{{{body}}} -- Work
{{{body}}} -- No Work
```

### CODE REVIEW

**Comment by zeke** [comment]
Weird. Can you add a test for this?

**Comment by TiagoDanin** [comment]
Done!

**Comment by zeke** [comment]
Thanks. Looks like CI is failing though.

**Comment by TiagoDanin** [comment]
image
No problem with Node 9.

**Pull request closed without merging**
